
version: '3.2'

networks:
  hlffabric1:
    external: 
      name: hlffabric1

services:

  peer0_org2:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == intel-sawtooth
    image: hyperledger/fabric-peer:latest
    hostname: peer0.org2.example.com
    container_name: peer0.org2.example.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_NETWORKID=hlffabric1
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hlffabric1
      - CORE_PEER_ADDRESSAUTODETECT=true
      # - CORE_PEER_GOSSIP_ORGLEADER=false
      # - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
      #- CORE_LEDGER_STATE_STATEDATABASE=LevelDB
      - CORE_LOGGING_LEVEL=CRITICAL
      - CORE_LOGGING_GOSSIP=${CORE_LOGGING_GOSSIP}
      - CORE_LOGGING_MSP=CRITICAL
      # - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
      # TLS settings
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
      - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.org2.example.com:7052
      - CORE_PEER_ID=peer0.org2.example.com
      - CORE_PEER_ADDRESS=peer0.org2.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0_org2:5984
    volumes:
      - /var/run/:/host/var/run/
      # - $GOPATH/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric/
      # - ../crypto-config/:/var/hyperledger/config
      - /home/ubuntu/efsmount/mynetwork/certs/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp:/var/hyperledger/msp
      - /home/ubuntu/efsmount/mynetwork/certs/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls:/var/hyperledger/tls
      - /home/ubuntu/efsmount/mynetwork/certs/crypto-config/peerOrganizations/org2.example.com/users:/var/hyperledger/users
      - /home/ubuntu/efsmount/mynetwork/certs/config/:/var/hyperledger/config
      - /home/ubuntu/efsmount/mynetwork/peer0.org2.example.com:/var/hyperledger/production
    command: peer node start
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    depends_on:
      - couchdb0
    networks:
      hlffabric1:
        aliases:
          - peer0.org2.example.com
    ports:
      - 9051:7051
      - 9053:7053
      
  peer1_org2:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == intel-sawtooth
    image: hyperledger/fabric-peer:latest
    hostname: peer1.org2.example.com
    container_name: peer1.org2.example.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_NETWORKID=hlffabric1
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hlffabric1
      - CORE_PEER_ADDRESSAUTODETECT=true
      # - CORE_PEER_GOSSIP_ORGLEADER=false
      # - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
      #- CORE_LEDGER_STATE_STATEDATABASE=LevelDB
      - CORE_LOGGING_LEVEL=CRITICAL
      - CORE_LOGGING_GOSSIP=${CORE_LOGGING_GOSSIP}
      - CORE_LOGGING_MSP=CRITICAL
      # - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
      # TLS settings
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
      - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
      - CORE_PEER_CHAINCODELISTENADDRESS=peer1.org2.example.com:7052
      - CORE_PEER_ID=peer1.org2.example.com
      - CORE_PEER_ADDRESS=peer1.org2.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.example.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1_org2:5984
    volumes:
      - /var/run/:/host/var/run/
      # - $GOPATH/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric/
      # - ../crypto-config/:/var/hyperledger/config
      - /home/ubuntu/efsmount/mynetwork/certs/crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/msp:/var/hyperledger/msp
      - /home/ubuntu/efsmount/mynetwork/certs/crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/tls:/var/hyperledger/tls
      - /home/ubuntu/efsmount/mynetwork/certs/crypto-config/peerOrganizations/org2.example.com/users:/var/hyperledger/users
      - /home/ubuntu/efsmount/mynetwork/certs/config/:/var/hyperledger/config
      - /home/ubuntu/efsmount/mynetwork/peer1.org2.example.com:/var/hyperledger/production
    command: peer node start
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    depends_on:
      - couchdb0
    ports:
      - 10051:7051
      - 10053:7053
    networks:
      hlffabric1:
        aliases:
          - peer1.org2.example.com
